# -*- coding: utf-8 -*-
{
    'name': "Tokiku",
    'summary': "Tokiku Customization",
    'description': "Tokiku Customization",
    'author': "CENOQ Corp.",
    'website': "http://www.cenoq.com",
    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/master/odoo/addons/base/module/module_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',
    # any module necessary for this one to work correctly
    'depends': ['base', 'biznavi', 'backend_theme_v10', 'project', 'product', 'contract', 'purchase', 'stock', 'mrp',
                'account', 'sale', 'document',
                'l10n_tw', 'web_sheet_full_width', 'web_listview_range_select', 'web_listview_sticky_header',
                'web_widget_grid', 'web_domain_field', 'web_m2x_options', 'web_widget_many2many_tags_multi_selection',
                'display_import_button'],
    # always loaded
    'data': [
        'security/tokiku_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/data.xml',
        'views/res_partner.xml',
        'views/res_user.xml',
        'views/project_views.xml',
        'views/contract_views.xml',
        'views/panel_views.xml',
        'views/preparation_views.xml',
        'views/assembly_order_views.xml',
        'views/production_record_views.xml',
        'views/order_panel_views.xml',
        'views/atlas_view.xml',
        'views/mold_view.xml',
        'views/demand_view.xml',
        'views/order_views.xml',
        'views/product_views.xml',
        'views/stock_views.xml',
        'views/mrp_views.xml',
        'views/webclient_templates.xml',
        'views/stock_picking_views.xml',
        'views/stock_move_views.xml',
        'views/menu.xml',
        'views/tokiku.xml',
        'views/account_invoice_views.xml',
        'views/installation_views.xml',
        'wizard/reserved_payment.xml',
        'wizard/order_wizard_view.xml',
        'wizard/new_version_atlas.xml',
        'wizard/panel_order_select_wizard.xml',
        'wizard/material_unit_price.xml',
        'wizard/material_sum.xml',
        'wizard/picking_product_select.xml',
        'wizard/paint_unit_price.xml',
        'wizard/paint_sum.xml',
        'wizard/assembly_select_wizard.xml',
        'wizard/assembly_unit_price.xml',
        'wizard/install_select_wizard.xml',
        'wizard/install_unit_price.xml',
        'reports/tokiku_report.xml',
        'reports/order_report.xml',
        'reports/tokiku_order_report.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
    'qweb': [
        "static/src/xml/*.xml",
    ],
}
